apiVersion: v1
kind: Service
metadata:
  name: sdc-rtc
  namespace: default
  labels:
    app: sdc-rtc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: sdc-rtc
---
apiVersion: v1
kind: Service
metadata:
  name: sdc-rtc-external
  namespace: default
  labels:
    app: sdc-rtc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:792028225466:certificate/7675d014-fdfd-491a-9c6f-6f6f6b318905
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
  selector:
    app: sdc-rtc