apiVersion: v1
kind: Service
metadata:
  name: sdc-rtc
  namespace: default
  labels:
    app: sdc-rtc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: sdc-rtc
---
apiVersion: v1
kind: Service
metadata:
  name: sdc-rtc-external
  namespace: default
  labels:
    app: sdc-rtc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-064f0d393c19922f7
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: sdc-rtc
