apiVersion: v1
kind: Service
metadata:
  name: sdc-rtc
  namespace: default
  labels:
    app: sdc-rtc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: sdc-rtc
---
apiVersion: v1
kind: Service
metadata:
  name: sdc-rtc-external
  namespace: default
  labels:
    app: sdc-rtc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: sdc-rtc
